### ISSUE TITLE
Material for RSECon 

### ISSUE THREAD

**Issue by mattjbr123** [NERC-CEH/rse_group#26]
Not sure if 'Issues' is the right place for this, but following the guidance at https://ben.balter.com/2020/08/14/tools-of-the-trade/ (discussed in https://github.com/NERC-CEH/rse_group/discussions/16#discussion-6847744) it seems more appropriate than a discussion given it can have a 'closed' status/is time-limited. Happy for it to be moved. 

A place to collect thoughts and/or material for/on our attendance at RSECon, and note any sessions of particular interest.

For example:

- @metazool has submitted an abstract for a presentation about the first 100 days of a new RSE team
- There's a "Finding the weather and climate RSE community" birds-of-a-feather session that might be worth contributing to (_Originally posted by @colinsauze in https://github.com/NERC-CEH/rse_group/discussions/15#discussioncomment-10008135_)
The organisers of the BoF Session have reached out to us via @cmtso via email and requested that we provide a 'quick overview' containing: 
  - What do we do? What are the problems we solve?
  - How do our RSEs work?
  - What tools and approaches do we use?
  - What do we need/want from a Climate & Weather RSE community?
- Any other sessions of interest we all/some of us/one of us would like to attend?

**Comment by mattjbr123** [comment]
My first pass at what interests me. Lots of clashes, I will narrow down nearer the time.

## Tuesday 03/09/2024
- 11:15-11:45 Performant Python Patterns
- 12:00 - 12:15 Discovering and bridging knowledge gaps between research software engineering and software engineering research
- 12:15 - 12:30 Empowering Ambassadors of Good Practice: The Software Sustainability Institute Fellowship Programme
- 12:00 - 12:30 Advanced Python Testing - mocking, property based testing, snapshot testing
- 13:30 - 14:15 Demystifying Large Language Models
- 13:30 - 14:45 Effortlessly creating Python packages with good practices
- 13:45 - 14:00 A new RSE group - the first 100 days
- 16:20 - 17:05 Motivating and Meaningful Career Development for RSEs
- 16:35 - 17:05 Open science cloud infrastructure and training for communities in Latin America and Africa

## Wednesday 04/09/2024
- 11:15 - 12:00 Agile Methods for RSEs: A formula for scrum-driven software development in research?
- 12:00 - 12:30 On the Tension between Agile Methodologies and Research Software
- 11:45 - 12:00 Modern, interactive and impactful software documentation with Sphinx, MyST and the Diátaxis framework
- 13:30 - 14:15 Re-runnable code is all you need
- 14:15 - 14:45 Deciding on the ideal software environment -- Personal experiences with Docker, Anaconda, virtual machines, and servers
- 15:50 - 16:35 Towards adoption of FAIR4RS: equipping researchers with FAIR research software skills
- 16:50 - 17:05 Enhancing Real-Time Geospatial Big Data Processing and Presentation Through Cloud-Optimised Storage and Formats

## Thursday 05/09/2024
These are in 2 sessions... Unclear if each session is the same or it's one long sessions split into 2. Times here reflect first session of each. 
- 09:30 - 10:45 Intersectional EDIA and Allies: celebrating the highs and weathering the lows
- 11:00 - 12:30 Finding the Weather and Climate RSE Community - knowledge exchange and the next steps for the flock

**Comment by cmtso** [comment]
- What do we do? What are the problems we solve?
	- [Climate and land | UK Centre for Ecology & Hydrology (ceh.ac.uk)](https://www.ceh.ac.uk/our-science/science-challenges/climate-and-land)
	- [Hydro-Climate Risks | UK Centre for Ecology & Hydrology (ceh.ac.uk)](https://www.ceh.ac.uk/our-science/science-departments/hydro-climate-risks)
	- We use a lot of weather and climate model outputs for downstream research, from using weather data as input for hydrological models for flood and drought modelling, running land surface models to predict many things such as photosynthesis and wildfire, to using future climate scenarios to explore pathways of land use adaptations, air pollutant emissions and effects on biodiversity.
	- We coordinate the large UK land surface model (JULES), which forms part of the Met Office Unified model (UM)
	- We do some extreme weather modelling, such as hydrology nowcasting in Sub-saharan Africa: [Welcome to the Hydrology in Sub-Saharan Africa Portal | Hydrology in Sub-Saharan Africa Portal (ceh.ac.uk)](https://africa-hydrology.ceh.ac.uk/)
	- [unifhy-org/unifhy: A Unified Framework for Hydrology (github.com)](https://github.com/unifhy-org/unifhy)
- How do our RSEs work?
	- 
- What tools and approaches do we use?
	- 
- What do we need/want from a Climate & Weather RSE community?
	- Solving common challenges together--many similarities between climate modelling and land surface/hydrological/atmospheric chemistry modelling
	- Improve interoperability between these models for more flexible coupling/linking
	- Accessibility
	- Documentation
		- CMIP6
		- Frustrating to have to read all of it
		- Hard to have a quick play to make a start
	- Standards

**Comment by metazool** [comment]
There's also a [Leaders and Aspiring Leaders](https://virtual.oxfordabstracts.com/#/event/49081/program?session=106940&program&date=%222024-9-2%22) meeting the day before RSECon which is separate registration, I've signed up for that.

The main topic I want to bring to it is the question of RSE group handbooks - working norms, agile methods, whatever it is that they cover. I've had a couple of  convos about where they exist but are not public, but not for any specific reason...

**Comment by colinsauze** [comment]
@metazool  you might find this handbook from USRSE useful. A few things a little bit US specific, but most of it applies here too. 
https://kilthub.cmu.edu/articles/report/Hiring_Managing_and_Retaining_Data_Scientists_and_Research_Software_Engineers_in_Academia/24150825?file=42370305

**Comment by longr** [comment]
> There's also a [Leaders and Aspiring Leaders](https://virtual.oxfordabstracts.com/#/event/49081/program?session=106940&program&date=%222024-9-2%22) meeting the day before RSECon which is separate registration, I've signed up for that.
> 
> The main topic I want to bring to it is the question of RSE group handbooks - working norms, agile methods, whatever it is that they cover. I've had a couple of convos about where they exist but are not public, but not for any specific reason...

I will try and make this remotely, but even if I can't, I would suggest you reach out to @aharwood2 regarding agile methods and working norms.

**Comment by aharwood2** [comment]
We're doing a talk at RSE Con this year about agile methods for our RSEs so people are welcome to line up the questions if you are coming!

**Comment by metazool** [comment]
My "what interests me" list, work in progress!

## 02-09

RSE Leaders and Aspiring Leaders Meeting (separate registration, all afternoon from 12)

## 03-09

**07:30** Bhangra session!
**11:15** GraphQL 
**12:00** Advanced python testing OR knowledge gaps with software engineering research + Fellowship programme
**13:30** Effortless python packaging good practises but it clashes with my talk
**13:45** A new RSE Group - the first 100 days (who are these people)
**14:15** Good cookie cutters
**15:50** HPC environmental and social impact
**16:20** Mutation testing

## 04-09 

**11:15** Agile methods for research software 
**12:00** Tension between the above, interesting contrast of talks
**13:30** Re-runnable code
**14:15** Personal experiences of environment configuration
**15:50** Software quality indicators OR FAIR research software skills

## 05-09 

**07:30** Body conditioning!
**09:30** Unconference: Create New Communities
**11:00** Green RSEs? OR Weather and Climate BoF 
**14:00** Green RSEs? OR Weather and Climate BoF

**Comment by metazool** [comment]
100_days branch in this repo (currently contains a `beamer` outline in the `team` directory)

I'll add my take on a narrative version next to it and incorporate some of the text into the Pages version, might as well get re-use out of it https://nerc-ceh.github.io/rse_group/

**Comment by metazool** [comment]
Closing this as we're post-conference!

There's talk of a ScotRSECon next year which would be lovely
